### ISSUE TITLE
Error retrieving object

### ISSUE THREAD

**Issue by adomingues** [palantir/palantir-r-sdk#30]
Hi all,

first of all thank you for making this API for foundry available - us R users appreciate it :)

I was trying it but ran into an error which I can't figure out:

```r
library("foundry")
Sys.setenv(FOUNDRY_HOSTNAME = "company.palantirfoundry.com")
df <- datasets.read_table("somedata")
Error in self$api_client$stop_for_status(response) : {
  "errorCode": "INTERNAL",
  "errorName": "Default:Internal",
  "errorInstanceId": "0160f807-21f7-4dd9-b0fa-78a3c9f79782",
  "parameters": {}
} (HTTP 500).

```

As far as I can tell the token is set in the system and the object exists. I have also set up the object yaml file in  `~/.foundry`. Any idea as what the source of the error might be?

---

Two somewhat related questions:

1. `foundry.token`, currently I have it has a system variable, how to set it for an interactive session? 
2. Some of my datasets in Foundry are in json format. How to retrieve those?

---

Cheers

**Comment by AlexandreGuinaudeau** [comment]
Hi @adomingues,

We should improve the error message here, but we don't quite support all tabular datasets yet. I'll update this ticket when we do, in the meantime you can download the CSV or parquet files backing the dataset (see below) and load them with native R libraries.

1. You can either set your token with `options(foundry.token = "<my-foundry-token>")` or `Sys.setenv(FOUNDRY_TOKEN = "<my-foundry-token>")` - do either of these work for you?
2. `datasets.read_table` only work for tabular datasets (that have a schema, and render as a table in Foundry). For arbitrary datasets, you'll want to use ```somedata <- datasets.list_files("somedata")
downloaded_files <- datasets.download_files("somedata", somedata)``` which will download the files backing the dataset locally.

**Comment by adomingues** [comment]
Thanks @AlexandreGuinaudeau. the second solution, download files worked well for a test json. 

The Dataset objects are indeed trickier and `datasets.read_table` still doesn't work directly for tabular datatsets (I checked and they conform to your specs). For those files,  `downloaded_files <- datasets.download_files("somedata", somedata)`  output show many parquet files. Picking one and running this will work:

```r
somedata <- datasets.list_files("somedata")
downloaded_files <- datasets.download_files("somedata", "spark/part-random-number.parquet")

rio::import("/mnt/tmp/RtmpwEHw3b/somedata/spark/part-random-number.parquet") ## uses arrow
```

does retrieve the object, so that is a workable solution for now.

Cheers,
António
